### ISSUE TITLE
2 small frontend flaws: Footer layout + weirdly navigating the page

### ISSUE THREAD

**Issue by photkosee** [thelang-io/the#112]
**Describe the bug**

On the landing page https://thelang.io/ whenever users click to switch between windows and unix to show the cli, the page will be navigated to the top of the page (should not navigate to anywhere). It's routing to /# which is why it will navigated to the top of the page every time users switch the option.

On the doc page https://docs.thelang.io/examples/ the footer is not located at the bottom most of the page in the large screen (some padding between the footer and bottom most of the page is visible). Could have been solved by setting the body min height to full.

**To Reproduce**
Steps to reproduce the behavior (1st issue):

1. Go to https://thelang.io/
2. Scroll down to `Start using The in no time with powerful CLI` section
3. Try switching between windows/unix option
4. The page will be navigated to the top

**To Reproduce**
Steps to reproduce the behavior (2nd issue):

1. Go to https://docs.thelang.io/examples/
2. If you have a large enough screen, the footer should be noticed that it's not located at the bottom most of the page as it should be

**Expected behavior**

For the first issue, the page should stay still and just changing the output box

For the second issue, the footer should always be located at the top most

**Screenshots**

For the second issue:
![Screenshot (594)](https://github.com/user-attachments/assets/2457d243-7547-47ba-a847-550aa0240a18)

**Please complete the following information**
- Device: ASUS
- OS, OS Version, OS Word Size: Windows
- The Programming Language version: -

**Additional context**

I would love to help fixing these small frontend things if possible

**Comment by delasy** [comment]
@photkosee oh wow I haven't thought about this, the correct place to start with are these two repos: https://github.com/thelang-io/thelang.io and https://github.com/thelang-io/docs.thelang.io

For issue with docs you can just add `display: flex; flex-direction: column;` to body and then `flex-grow: 1;` to page-layout class.

Feel free to send PRs!

**Comment by photkosee** [comment]
@delasy Cool, I'll look at those and make pull requests. Would you mind me asking how I can run the whole thing locally to see the changes I made? I'm not familiar with this file system.

I made some changes and would like to see the results from my changes but kind of lost on how to do so. Thank you in advance.

**Comment by delasy** [comment]
@photkosee well for docs.thelang.io I have: https://github.com/thelang-io/docs.thelang.io/blob/main/CONTRIBUTING.md
And for thelang.io - this is just static files, you can modify it directly and open html page in your browser.

**Comment by photkosee** [comment]
@delasy Done :) I've open both pull requests. Please review them again before merging.

**Comment by delasy** [comment]
@photkosee thanks will check! I will close this issue now
